[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[build.environment]
  NODE_VERSION = "18"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 